spring.application.name=gestao-alunos

spring.datasource.url=jdbc:h2:file:C:/Users/asanto31/gestao-alunos/gestao-alunos/data/gestao-alunos;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000